### ISSUE TITLE
Comprehensive README

### ISSUE THREAD

**Issue by etangtw** [bsandhu1920/ThoughtWorks#1]
Try to assert more effort into your READMEs. Have the mindset of "I want to onboard users and developers of my application as easily as possible. I want this file to be the only thing they need to get this thing up and running". To be more specific:

- What does my application do?
- As a user, how would I run it?
- As a developer, where is the entry point of my code?

READMEs also make or break first impressions. A comprehensive one shows that you care about your codebase, and that it's a living document that grows as the code does.

**Comment by bsandhu1920** [comment]
Hey Eugene that's been updated!

**Comment by etangtw** [comment]
Hi Bal,

Cheers! Also, do you mind if you leave it up to me to close the issue in
the future? I may see something in your amendment which I'd like more
action on, so it'd be tidier to post in that same thread rather than open
up a new issue.


Regards,

Eugene

**Comment by bsandhu1920** [comment]
Hi Eugene,


Apologies for that I think I'd gotten ahead of myself at the time, I've left all of the other issues open!


Kind Regards,

Bal

________________________________
