### ISSUE TITLE
Naming (domain modelling) coupled with exercise

### ISSUE THREAD

**Issue by etangtw** [bsandhu1920/ThoughtWorks#5]
https://github.com/bsandhu1920/ThoughtWorks/blob/5dcd7e7d9a336454864bbb5f6a0076d90cea3a51/src/com/company/Triangles.java#L18-L22

Here, the exercise requirements have essentially taken over the code. You can see this by looking at the method name; it's named after the exercise requirement, **Easiest exercise ever**. Also, the method only appears to be concerned with satisfying only that one easy exercise, and is then never used again. At first glance this might make sense, but let's think about this a bit more:

Yes, the exercise wants us to print out an asterisk, but it also wants us to print out lines made out of asterisks, and then create shapes made out of asterisks! See anything in common? If we were programming in some hypothetical language created especially for this exercise, then perhaps we could get away with creating exercise-specific methods, but we're not; we're programming in Java, and in Java-land almost everything is heavily leaned towards OOP!

How do we take advantage of OOP? It starts by identifying what the possible classes are and their behaviours. Have a read through the exercise again, and try to find the nouns and verbs. Nouns are a good basis for identifying possible classes, verbs for methods.

It's a lot to wrap your head around, and I do not expect anyone to get it right quickly, not even myself.

**Comment by bsandhu1920** [comment]
Thank you for the feedback, I've attempted to orient the project towards more of an OOP structure. Please see some of the changes I've made, including the removal of most Static Methods.

If there are still major improvements to be made, I think I may get back to the books and dig a little deeper.
