### ISSUE TITLE
Static methods

### ISSUE THREAD

**Issue by etangtw** [bsandhu1920/ThoughtWorks#6]
This issue also feeds back into issue #5 in regards to modelling our application in an OOP way. There are many static methods in the application, and they introduce a bit of a problem to us when we try to take an object-oriented approach to solving our problems. I will not point out where these changes should be made, as I would like to see how you address issue #5 first. It may end up being that they have a place in our new version. If you do not know the effects of declaring variables and methods static, please read up on it then consider that keyword as you address issue #5.

**Comment by bsandhu1920** [comment]
Hey Eugene, I've responded to this issue in issue #5. Please let me know how that goes.
