### ISSUE TITLE
Viewing logic tied to business logic

### ISSUE THREAD

**Issue by etangtw** [bsandhu1920/ThoughtWorks#7]
https://github.com/bsandhu1920/ThoughtWorks/blob/d0ac765397b80bcf70edfedf399b6c0abe57667e/src/com/company/Triangles.java#L15-L26

I wanted to wait until a few other changes before introducing this one. The logic to display information (called the view/presentation logic) should ideally be split from the business logic (the meat of the logic that satisfies the requirements). Why do we want that? 

Imagine tomorrow if the client no longer wanted to display the exercises to the console, and instead wanted a proper GUI. How annoying would that be to make all those changes? Then, perhaps maybe the client changed their minds again and wanted a console display, after all! I'd be pulling my hair out over having to make those changes!

What if we could design our application such that we have a modular view component, whether it be a console display or GUI, and all they need are the exercises, and they'll print them out? How cool would that be? I'm not going to get you to create a graphical user interface, because that's crazy-talk, but I would like you to think about how you might create some component that knows how to take in any exercise, and display them to the console. That way, our Triangles, Diamonds and Numbers classes don't need to be concerned about printing, because that isn't their responsibility. Give that a go.

**Comment by etangtw** [comment]
Hint: you may need to start exploring Java Interfaces. They're awesome.

**Comment by bsandhu1920** [comment]
Hey Eugene,

Thanks for the feedback that actually makes a lot of sense, I hadn't really thought about the coupling between the logic and the actual presentation of the output.

Would this mean that the model in this situation would be producing the output in the form of a data structure and then passing that up to the presenter? I would imagine that we can no longer use the printStar method as frequently as I have been.

That being said, the printing methods are all self-contained and are simply called by the classes themselves, so I would only need to change that specific portion in the one class.

I'll definitely take a look into interfaces though, the concept seems very interesting.
